server:
  server_name: "user" # 服务名称
  go_module: "user" # go.mod 名称
  code_path: "./tmp" # 生成代码目录
  go_version: "1.20" # go 版本
mysql:
  addr: "127.0.0.1"
  user: "root"
  pwd: "wjlroot"
  port: "3306"
  db: "letter" # 数据库名
  table: "user" # 表名
  key: "id" # 表的主键id