server:
  # server name
  server_name: "email"
  # go.mod module path
  go_module: "letter"
  # code generation path
  code_path: "./tmp"
  # go version
  go_version: "1.19"
mysql:
  # addr
  addr: "0.0.0.0"
  # user
  user: "root"
  # password
  pwd: "wjlroot"
  # port
  port: "3306"
  # db name
  db: "letter"
  # table name
  table: "email"
  # primary key
  key: "id"