server:
  # server name
  server_name: "order"
  # go.mod module path
  go_module: "order"
  # code generation path
  code_path: "./tmp"
  # go version
  go_version: "1.20"
mysql:
  # addr
  addr: "0.0.0.0"
  # user
  user: "root"
  # password
  pwd: "wjlroot"
  # port
  port: "3306"
  # db name
  db: "ord"
  # table name
  table: "pay"
  # primary key
  key: "id"